default: &default
  adapter: postgresql
  encoding: utf8
  username: <%= Rails.application.credentials.db_user %>
  password: <%= Rails.application.credentials.db_password %>
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mdb_dev
  port: 5432

test:
  <<: *default
  database: mdb_test
  port: 5432

production:
  <<: *default
  database: mdb
  port: 5432
